pipeline {
    agent any

    tools {
        terraform 'terraform'
    }

    options {
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    environment {
        TF_DIR              = '43-azure-website-pt3/envs/dev'
        TF_IN_AUTOMATION    = 'true'
        ARM_TENANT_ID       = credentials('azure-tenant-id')
        ARM_SUBSCRIPTION_ID = credentials('azure-subscription-id')
    }

    stages {
        stage('Init & Validate') {
            steps {
                dir("${TF_DIR}") {
                    withCredentials([
                        usernamePassword(credentialsId: 'azure-spn-apply', usernameVariable: 'ARM_CLIENT_ID', passwordVariable: 'ARM_CLIENT_SECRET')
                    ]) {
                        sh 'terraform init'
                        sh 'terraform fmt -check'
                        sh 'terraform validate'
                    }
                }
            }
        }

        stage('Plan') {
            steps {
                dir("${TF_DIR}") {
                    withCredentials([
                        usernamePassword(credentialsId: 'azure-spn', usernameVariable: 'ARM_CLIENT_ID', passwordVariable: 'ARM_CLIENT_SECRET')
                    ]) {
                        sh 'terraform plan -out=tfplan'
                    }
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: "${TF_DIR}/tfplan", fingerprint: true
                }
            }
        }

        stage('Approval') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    input message: 'Review the plan. Deploy to Azure?'
                }
            }
        }

        stage('Apply') {
            steps {
                dir("${TF_DIR}") {
                    withCredentials([
                        usernamePassword(credentialsId: 'azure-spn', usernameVariable: 'ARM_CLIENT_ID', passwordVariable: 'ARM_CLIENT_SECRET')
                    ]) {
                        sh 'terraform apply -auto-approve tfplan'
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}