pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    environment {
        TF_DIR = '43-azure-website-pt3/envs/dev'
        
        ARM_TENANT_ID       = credentials('azure-tenant-id')
        ARM_SUBSCRIPTION_ID = credentials('azure-subscription-id')
    }

    stages {
        stage('Init & Validate') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform init'
                    
                    sh 'terraform fmt -check'
                    
                    
                    sh 'terraform validate'
                    
                    sh 'tflint -f compact'
                }
            }
        }

        stage('Plan') {
            steps {
                dir("${TF_DIR}") {
                    withCredentials([
                        usernamePassword(credentialsId: 'azure-spn-plan', usernameVariable: 'ARM_CLIENT_ID', passwordVariable: 'ARM_CLIENT_SECRET')
                    ]) {
                        sh 'terraform plan -out=tfplan'
                    }
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: "${TF_DIR}/tfplan", fingerprint: true
                }
            }
        }

        stage('Approval for Apply') {
            steps {
                input message: 'Do you want to apply the infrastructure changes?', ok: 'Deploy'
            }
        }

        stage('Apply') {
            steps {
                dir("${TF_DIR}") {
                    withCredentials([
                        usernamePassword(credentialsId: 'azure-spn-apply', usernameVariable: 'ARM_CLIENT_ID', passwordVariable: 'ARM_CLIENT_SECRET')
                    ]) {
                        sh 'terraform apply -auto-approve tfplan'
                    }
                }
            }
        }
    }
}
