replicaCount: 3
springProfile: dev
image:
  repository: busybox
  tag: stable
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  host: api.dev.task.local
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
