apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}
  labels:
    type: {{ .Values.pvType}}
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - {{ .Values.accessMode }}
  hostPath:
    path: "/mnt/data"