apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}