apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-svc
  labels:
    app: {{ .Values.api.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.api.name }}