apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: {{ .Values.protocol }}
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPortport }}