pipeline {
    agent any

    environment {
        AWS_REGION     = 'eu-central-1'
        ECR_REGISTRY   = '858986858999.dkr.ecr.eu-central-1.amazonaws.com'
        ECR_REPOSITORY = 'dev-task-api'
        ECS_CLUSTER    = 'dev-cluster'
        ECS_SERVICE    = 'dev-task-api-service'
        APP_DIR        = '39-jenkins-pt3/app'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    dir("${APP_DIR}") {
                        echo "Building image with tag ${BUILD_NUMBER}..."
                        dockerImage = docker.build("${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_NUMBER}")
                    }
                }
            }
        }
        stage('Push to ECR') {
            steps {
                script {
                    echo "Logging into AWS ECR using IAM Role..."
                    sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}"
                    
                    echo "Pushing image to AWS ECR..."
                    dockerImage.push()
                    dockerImage.push('latest')
                }
            }
        }

        stage('Deploy to ECS Fargate') {
            steps {
                script {
                    echo "Updating ECS service..."
                    sh """
                    aws ecs update-service \
                        --cluster ${ECS_CLUSTER} \
                        --service ${ECS_SERVICE} \
                        --force-new-deployment \
                        --region ${AWS_REGION}
                    """
                }
            }
        }
    }
    
    post {
        always {
            echo "Cleaning up local images..."
            sh "docker rmi ${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_NUMBER} || true"
        }
        success {
            echo "Success! New application version deployed."
        }
        failure {
            echo "Deployment failed. Check the logs."
        }
    }
}