pipeline {
    agent any

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'prod'], description: 'Target environment')
    }

    environment {
        AWS_REGION     = 'eu-central-1'
        ECR_REGISTRY   = '858986858999.dkr.ecr.eu-central-1.amazonaws.com'
        APP_DIR        = '39-jenkins-pt3/app'
        
        DEPLOY_ENV     = "${params.ENVIRONMENT}"
        ECR_REPOSITORY = "${params.ENVIRONMENT}-task-api"
        ECS_CLUSTER    = "${params.ENVIRONMENT}-cluster"
        ECS_SERVICE    = "${params.ENVIRONMENT}-task-api-service"
    }

    stages {
        stage('Build Image') {
            steps {
                script {
                    dir("${APP_DIR}") {
                        dockerImage = docker.build("${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_NUMBER}")
                    }
                }
            }
        }

        stage('Push to ECR') {
            steps {
                script {
                    sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}"
                    sh "docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_NUMBER}"
                    sh "docker tag ${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_NUMBER} ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
                    sh "docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
                }
            }
        }

        stage('Approval') {
            when {
                expression { DEPLOY_ENV == 'prod' }
            }
            steps {
                input message: "Deploy version ${BUILD_NUMBER} to PRODUCTION?", ok: "Deploy"
            }
        }

        stage('Deploy to ECS') {
            steps {
                script {
                    sh """
                    aws ecs update-service \
                        --cluster ${ECS_CLUSTER} \
                        --service ${ECS_SERVICE} \
                        --force-new-deployment \
                        --region ${AWS_REGION}
                    """
                }
            }
        }
    }

    post {
        always {
            sh "docker rmi ${ECR_REGISTRY}/${ECR_REPOSITORY}:${BUILD_NUMBER} || true"
            sh "docker rmi ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest || true"
        }
    }
}